### ISSUE TITLE
Feature Request: Brandmark / Logo

### ISSUE THREAD

**Issue by mbsouth** [liuch/dmarc-srg#162]
A brandmark / logo in the header, to the left of the menu, would be a great thing.

The image path / link could be implemented as an option in the config.

Jm2c

**Comment by liuch** [comment]
I might add an empty header element before the nav element. Using custom_css you can put a logo there and style it as you want. Something like this: `<header><div class="logo"></div><div class="company-name"></div></header>`

CSS example:
```css
  nav .logo { background-image: url(/path/to/your/logo.png); ... }
  nav .company-name:before { content: "your text here"; ... }
```
